# -*- coding: utf-8 -*-
"""Untitled45.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10NOaRP3IcA8LReFZj3PtVZLSujNDY2Kz
"""

import pandas as pd
#read the csv file as a dataframe
input_dataframe=pd.read_csv('Sample_input_data.csv')

#display the sample data
input_dataframe

#change the amount column according to the type column (i.e if player has win it's counted as loss for casino)
input_dataframe.loc[input_dataframe.type=='win','amount']=-1*input_dataframe['amount']

#update the amount with the ante value according to the game played (i.e poker --> amount+2, blackjack --> amount+1) 
input_dataframe.loc[input_dataframe.game_name=='poker','amount']=input_dataframe['amount']+2
input_dataframe.loc[input_dataframe.game_name=='blackjack','amount']=input_dataframe['amount']+1

#remove unneccesary columns from the dataframe (pre-processing task)
clean_input_dataframe=input_dataframe[['player_id','amount']].copy()

#create a pivot table to show the individual player's contribution in casino's profit amount
casino_profit_table = clean_input_dataframe.pivot_table(index =['player_id'],
                       values =['amount'],
                       aggfunc ='sum')

#convert the pivot table into dataframe and add a new column which displays the individual player's contribution in casino's profit amount in percentage
casino_profit_dataframe=pd.DataFrame(data=casino_profit_table)
casino_profit_dataframe['profit_in_perc']=(casino_profit_dataframe['amount']/casino_profit_dataframe['amount'].sum())*100

#sort the dataframe in descending order according to percentage of contribution in total profit by individual player 
sorted_casino_profit_dataframe=casino_profit_dataframe.sort_values(by=['profit_in_perc'],ascending=False)

#display the top 10% of the total players which were most profitable for the casino
sorted_casino_profit_dataframe[:int(len(df4)/10)]